mode: daemonset

image:
  repository: otel/opentelemetry-collector-contrib
  tag: 0.99.0  # Replace with latest or desired version

config:
  receivers:
    filelog:
      include:
        - /var/log/pods/*/*/*.log
      include_file_name: false
      include_file_path: true
      start_at: beginning
      operators:
        - type: json_parser
          timestamp:
            parse_from: attributes.time
            layout: '%Y-%m-%dT%H:%M:%S.%LZ'

  processors:
    batch: {}
    k8sattributes:
      extract:
        metadata:
          - k8s.pod.name
          - k8s.namespace.name
          - k8s.node.name
          - k8s.pod.uid
          - k8s.container.name
          - k8s.cluster.name

  exporters:
    loki:
      endpoint: http://loki.monitoring.svc:3100/loki/api/v1/push
      labels:
        resource:
          - k8s.namespace.name
          - k8s.pod.name
          - k8s.container.name

  service:
    pipelines:
      logs:
        receivers: [filelog]
        processors: [k8sattributes, batch]
        exporters: [loki]

extraVolumes:
  - name: varlogpods
    hostPath:
      path: /var/log/pods

extraVolumeMounts:
  - name: varlogpods
    mountPath: /var/log/pods
    readOnly: true
