apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: NodePort
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80            # Port exposed externally (NodePort maps to this)
      targetPort: 80    # Port your Flask app is running on inside the pod
      nodePort: 30629